# Site settings
title: Andrei Fajardo 
url: "http://anerdi.ca"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave someone empty to disable it
google_analytics: 
disqus_shortname: 
